---
title: "Lab 1 R Markdown"
author: "Manuel Vazquez, Tingyu Zou, Errol Kaylor"
date: "1/19/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("here")
library("rio")
library("tidyverse")
library("ggpubr")
library("dplyr")
library("tidytext")
```

# 1. Initial Exploration

```{r }
# import the data
data <- import(here("data","rstats_tweets.rds"))
```

## Create histograms

I believe the histogram with 50 bins provides the best representation of the data. It communicates a similar distribution compared to the other histograms with more granual bins (bins of 100 and 150) while still easy to read. 

```{r }

hist1 <- data %>%
ggplot (aes(display_text_width)) +
  geom_histogram(fill = "blue",
                 color = "white",
                 alpha = 0.6,
                 bins = 10) +
  labs(title="Bins = 10") +
  theme_minimal()

hist2 <- data %>%
ggplot (aes(display_text_width)) +
  geom_histogram(fill = "blue",
                 color = "white",
                 alpha = 0.6,
                 bins = 50) +
  labs(title = "Bins = 50") +
  theme_minimal()

hist3 <- data %>%
ggplot (aes(display_text_width)) +
  geom_histogram(fill = "blue",
                 color = "white",
                 alpha = 0.8,
                 bins = 100) +
  labs(title = "Bins = 100") +
  theme_minimal()

hist4 <- data %>%
ggplot (aes(display_text_width)) +
  geom_histogram(fill = "blue",
                 color = "white",
                 alpha = 1.2,
                 bins = 150) +
  labs(title = "Bins = 150") +
  theme_minimal() 

ggarrange(hist1, hist2, hist3, hist4 )
```

```{r Look-for-“plot”}
data2 <- data %>%
  mutate(LFplot = str_detect(text,"plot")) 
data2$LFplot %>% 
  mean()
```



```{r }
text <- select(data, text)
text_tidy_words <- text %>% 
  unnest_tokens(word, text)

```

```{r}
TTW <- text_tidy_words %>% 
  anti_join(stop_words) %>%
  filter(word != "t.co",
         word != "https",
         word != "http",
         word != "rt", 
         word != "rstats") %>% 
  count(word, sort = TRUE) 

TTW %>% 
  mutate(word = reorder(word,n)) %>% 
  slice(1:15) %>% 
  ggplot(aes(n,word))+
  geom_col()+
  theme_minimal()
```


```{r}
TTW %>% 
  mutate(word= reorder(word, n)) %>%
  slice(1:15) %>% 
  ggplot(aes(n, word)) +
  geom_col(fill = "cornflowerblue")+
  theme_minimal()+
  labs(title ="Word frequencies in posts", subtitle = "Top 15 words displayed", caption = "Data from Mike Kearny, distributed via #tidytuesday")+
  xlab("Count Across All Posts")+
  ylab("Word")

```
